- jsk_interactive_markers/jsk_interactive_marker/euslisp/robot-actions.l
implement move object action
this action is called with these markers
* object model interactive marker
* bounding box interactive marker
> Implement move object action

- jsk_rqt_plugins/bin/rqt_drc_mini_maxwell
- jsk_rqt_plugins/plugin.xml
- jsk_rqt_plugins/src/jsk_rqt_plugins/mini_maxwell.py
* when high speed link is available
* when high speed link is down
> [jsk_rqt_plugins] Add simple viewer to visualize mini maxwell status.

- jsk_interactive_markers/jsk_interactive_marker/euslisp/robot-actions.l
oneclick and box movement is almost same code.
so I pass arguments from one click to box movement.
> modify robot-actions and pass the msg to box movement

- jsk_interactive_markers/jsk_interactive_marker/euslisp/robot-actions.l
reverse target-cds-list to prevent ik failure in next step
> Prevent ik failure

- jsk_rviz_plugins/src/torus_array_display.cpp
- jsk_rviz_plugins/src/torus_array_display.h
> Make torus more smooth and add uv-smooth parameter

- jsk_rviz_plugins/src/polygon_array_display.cpp
- jsk_rviz_plugins/src/polygon_array_display.h
Add new feature to PolygonArrayDisplay to show the normal of the polygons.
> [jsk_rviz_plugins] Add "Show Normal" to PolygonArrayDisplay

- jsk_rviz_plugins/src/torus_array_display.cpp
- jsk_rviz_plugins/src/torus_array_display.h
> add normal option for torus display

- jsk_rviz_plugins/catkin.cmake
- jsk_rviz_plugins/msg/RecordCommand.msg
- jsk_rviz_plugins/plugin_description.xml
- jsk_rviz_plugins/src/record_action.cpp
- jsk_rviz_plugins/src/record_action.h
> add record action panel

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
> add bounding box marker version and line version

- jsk_interactive_markers/jsk_interactive_marker/launch/bounding_box_cropper.launch
> add bounding box cropper example launch

- jsk_rviz_plugins/scripts/pointcloud_information.py
> add publishing pointcloud information as overlay text

- jsk_rviz_plugins/src/pie_chart_display.cpp
- jsk_rviz_plugins/src/pie_chart_display.h
fix for https://github.com/jsk-ros-pkg/jsk_visualization/issues/301#issuecomment-72314159
> [jsk_rviz_plugins] Draw PieChart at the first time

- jsk_rviz_plugins/scripts/tf_diff_text.py
> [jsk_rviz_plugins] Add utility script to visualize difference between to tf frames on rviz

- jsk_rqt_plugins/bin/rqt_service_buttons
- jsk_rqt_plugins/package.xml
- jsk_rqt_plugins/plugin.xml
- jsk_rqt_plugins/resource/service_button_layout.yaml
- jsk_rqt_plugins/src/jsk_rqt_plugins/button.py
Add simple rqt plugin to list buttons to call empty service and configurable by yaml file
> [jsk_rqt_plugins] Add simple rqt plugin to list buttons to call empty service

- jsk_rqt_plugins/resource/service_button_layout.yaml
- jsk_rqt_plugins/src/jsk_rqt_plugins/button.py
> [jsk_rqt_plugins] Support image for button icons in rqt_service_button

- jsk_rqt_plugins/bin/rqt_image_view2
- jsk_rqt_plugins/launch/rqt_image_view2.launch
- jsk_rqt_plugins/package.xml
- jsk_rqt_plugins/plugin.xml
- jsk_rqt_plugins/src/jsk_rqt_plugins/button.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/image_view2_wrapper.py
rqt wrapper of image_view2.
It retrieves image_marked topic from image_view2 and publish event topic to image_view2
> [jsk_rqt_plugins] image_view2 rqt wrapper

- jsk_rqt_plugins/resource/rqt_image_view2_button.perspective
perspective file for this layout
> [jsk_rqt_plugins] Add perspective to combine rqt_image_view2 and rqt_service_button

- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
Fix service /transformable_interactive_server/get_dimensions to set marker type.
> Fix get dims srv

- jsk_rqt_plugins/src/jsk_rqt_plugins/image_view2_wrapper.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/label.py
> [jsk_rqt_plugins] Add settings button and remove combo box from top view

- jsk_rqt_plugins/bin/rqt_status_light
- jsk_rqt_plugins/plugin.xml
- jsk_rqt_plugins/src/jsk_rqt_plugins/status_light.py
> [jsk_rqt_plugins] Add simple widget to visualize status(std_msgs/Int32)

- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractiveSetting.cfg
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_object.h
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_object.cpp
to change control orientation mode(inherit, fixed, view_facing)
> add configure for change control orientation mode

- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_object.h
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_object.cpp
can change control offset by pub to /set_control_pose
> Change interactive control origin

- .travis.yml
- jsk_rviz_plugins/README.md
- jsk_rviz_plugins/samples/sparse_occupancy_grid_sample.py
- jsk_rviz_plugins/src/rviz_util.h
- jsk_rviz_plugins/src/simple_occupancy_grid_array_display.cpp
* support auto coloring
* update README.md
* use smaller number of CPUs on travis
> [jsk_rviz_plugins] Support auto coloring in SimpleOccupancyGridArray

- jsk_rqt_plugins/src/jsk_rqt_plugins/image_view2_wrapper.py
1. Use signal to tell redraw event from subscription callback
2. Fix periodic duration to call updateTopics
> [jsk_rqt_plugins] Optimize image_view2_wrapper:

- jsk_interactive_markers/jsk_interactive_marker/src/urdf_control_marker.cpp
> [jsk_interactive_marker/urdf_control_marker] Transform pose respected to fixed_frame_id  when urdf_control_marker is moved by topic interface

- jsk_rqt_plugins/src/jsk_rqt_plugins/image_view2_wrapper.py
for https://github.com/jsk-ros-pkg/jsk_demos/issues/544
> [jsk_rqt_plugins/iamge_view2_wrapper] Use thread to update image topic list isntead of QTimer not to hung up rqt_gui

- jsk_rviz_plugins/README.md
- jsk_rviz_plugins/msg/Pictogram.msg
- jsk_rviz_plugins/samples/pictogram.py
- jsk_rviz_plugins/src/pictogram_display.cpp
- jsk_rviz_plugins/src/pictogram_display.h
- Add Mode (Pictogram_mode, String_mode)
- Add TTL (if ttl is 0, show eternally)
> [jsk_rviz_plugins] add String PopupMode for Pictogram

- jsk_rviz_plugins/README.md
- jsk_rviz_plugins/msg/Pictogram.msg
- jsk_rviz_plugins/samples/pictogram.py
- jsk_rviz_plugins/src/pictogram_array_display.cpp
- jsk_rviz_plugins/src/pictogram_display.cpp
- jsk_rviz_plugins/src/pictogram_display.h
> Add rotate speed param to pictogram

- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
when service interface is used
> [jsk_interactive_marker/footstep_marker] Fix projection of footprint

- jsk_interactive_markers/jsk_interactive_marker/src/urdf_control_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker_main.cpp
1) use JSK_ROS_INFO, JSK_ROS_ERROR to output debug message
2) Fix handling of tf lookup exception not to ignore addChildLinkNames
> [jsk_interactive_marker/urdf_model_marker] Fix furutaractive when it fails to lookup tf transformation.

- jsk_rqt_plugins/sample/sample_histogram.launch
- jsk_rqt_plugins/sample_scripts/sample_hist_pub.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
You can specify histogram with x-values by jsk_recognition_msgs/HistogramWithRange
> [jsk_rqt_plugins/histogram_plot] Support jsk_recognition_msgs/HistogramWithRange message to specify x-axis values

- jsk_rqt_plugins/sample/sample_histogram.launch
- jsk_rqt_plugins/sample_scripts/sample_hist_pub.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
> [jsk_rqt_plugins/rqt_histogram_plot] Support legend

- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
In order to overlay the image on rviz
> [jsk_rqt_plugins/rqt_histogram_plot] Publish rendered image from rqt_histogram_plot.

- jsk_rviz_plugins/cfg/polygon_array_sample.rviz
- jsk_rviz_plugins/launch/polygon_array_sample.launch
- jsk_rviz_plugins/samples/polygon_array_sample.py
```
roslaunch jsk_rviz_plugins polygon_array_sample.launch
```
> [jsk_rqt_plugins] Add sample launch for PolygonArray

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
Publish tf with interactive marker interface.
> [jsk_interactive_marker/marker_6dof] Publish tf frame from interactive marker

- jsk_rviz_plugins/config/bounding_box_sample.rviz
- jsk_rviz_plugins/launch/boundingbox_sample.launch
- jsk_rviz_plugins/samples/bounding_box_sample.py
- jsk_rviz_plugins/src/bounding_box_array_display.cpp
- jsk_rviz_plugins/src/bounding_box_array_display.h
Also sample launch file is available.
```
roslaunch jsk_rviz_plugins boundingbox_sample.launch
```
> [jsk_rviz_plugins/BoundingBoxArray] Update coloring method to support coloring by values and labels.

- jsk_rqt_plugins/CMakeLists.txt
- jsk_rqt_plugins/src/jsk_rqt_plugins/label.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/util.py
- jsk_rqt_plugins/test/test_util.py
Show candidate field (whose data type is string) of topics.
> [jsk_rqt_plugins] Add util to get slot field

- jsk_rviz_plugins/src/twist_stamped_display.cpp
> [jsk_rviz_plugins/TwistStamped] Decide circle thickness according to radius of circle

- jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker.cpp
see https://github.com/jsk-ros-pkg/jsk_demos/issues/1042
> add wait for trans to avoid tf nan error

- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
> [jsk_rqt_plugins/plot_2d] Show grid

- jsk_rqt_plugins/sample/sample_2dplot.launch
- jsk_rqt_plugins/sample_scripts/sample_2d_plot.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
* normal rqt_plot is a tool to visualize 1-D data as 2-D in time-series
* rqt_2d_plot is a tool to visualize 2-D data. It only supports `jsk_recognition_msgs/PlotData`
```
$ rosmsg show jsk_recognition_msgs/PlotData
std_msgs/Header header
uint32 seq
time stamp
string frame_id
float32[] xs
float32[] ys
```
> [jsk_rqt_plugins/rqt_2d_plot] Add sample

- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
```
$ rosrun jsk_rqt_plugins rqt_2d_plot -h
usage: Plot2D [-b BINDING] [--clear-config] [--force-discover] [-h]
[--reload-import] [-t] [-v] [--line] [--fit-line]
[--xtitle XTITLE] [--ytitle YTITLE] [--no-legend] [--sort-x]
[topics]
Options for GUI instance:
-b BINDING, --qt-binding BINDING
choose Qt bindings to be used [pyqt|pyside]
--clear-config        clear the configuration (including all perspectives
and plugin settings)
--force-discover      force a rediscover of plugins
-h, --help            show this help message and exit
--reload-import       reload every imported module
-t, --on-top          set window mode to always on top
-v, --verbose         output qDebug messages
Options for rqt_histogram plugin:
topics                Topics to plot
--line                Plot with lines …
```
> [jsk_rqt_plugins] Add more plot options for rqt_2d_plot

- doc/add_img_tables_to_index.py
- doc/conf.py
> Add image gallery to index of document

- jsk_rqt_plugins/sample/sample_2dplot.launch
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
> [jsk_rqt_plugins] Fit line to date by ransac

- jsk_rviz_plugins/config/link_marker_publisher_sample.rviz
- jsk_rviz_plugins/launch/link_marker_publisher_sample.launch
- jsk_rviz_plugins/scripts/link_marker_publisher.py
It is a sample script to change color of a link of robot model use rviz marker.
We should be able to change color of link which touches environment.
> [jsk_rviz_plugins] Add script to publish marker of a robot link with specified color

- jsk_rviz_plugins/config/contact_state_marker_sample.rviz
- jsk_rviz_plugins/launch/contact_state_marker_sample.launch
- jsk_rviz_plugins/samples/contact_state_sample.py
- jsk_rviz_plugins/scripts/contact_state_marker.py
@eisoku9618 
https://github.com/start-jsk/rtmros_common/pull/834
contact_state_marker.pyを使えばプログラム書かなくて可視化できるはずなので、試してみてください.
> [jsk_rviz_plugins] contact_state_marker.py to visualize hrpsys_ros_bridge/ContactStatesStamped

- jsk_rviz_plugins/scripts/motor_states_temperature_decomposer.py
and Fix for joints which does not have limit attribute.
> [jsk_rviz_plugins/motor_states_temparature_decomposer] Decrease cpu load by queue_size=1.

- jsk_rqt_plugins/src/jsk_rqt_plugins/yes_no_button.py
> [jsk_rqt_plugins] Avoid already advertised error for rqt_yn_btn

- jsk_rviz_plugins/src/bounding_box_array_display.cpp
> [jsk_rviz_plugins/BoundingBoxArray] Fix coords orientation.

- jsk_rviz_plugins/scripts/rosconsole_overlay_text.py
Added:
- jsk_rviz_plugins/scripts/rosconsole_overlay_text.py
> [jsk_rviz_plugins] Add script to visualize /rosout on rviz

- .travis.rosinstall
- .travis.yml
- jsk_rviz_plugins/src/torus_array_display.cpp
- jsk_rviz_plugins/src/torus_array_display.h
It requires https://github.com/jsk-ros-pkg/jsk_recognition/pull/1379
> [jsk_rviz_plugins] Do not visualize failure=true toruses.

- jsk_rviz_plugins/src/torus_array_display.cpp
Modified:
jsk_rviz_plugins/src/torus_array_display.cpp
> [jsk_rviz_plugins] Clear arrow of torus when it is disabled

- jsk_rviz_plugins/scripts/rosconsole_overlay_text.py
Modified:
- jsk_rviz_plugins/scripts/rosconsole_overlay_text.py
> [jsk_rviz_plugins] Add regular expression interface to specify target node in rosconsole_overlay_text.py

- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
- jsk_interactive_markers/jsk_interactive_marker/package.xml
Closes #551
Modified:
- jsk_interactive_markers/jsk_interactive_marker/package.xml
> Fix problem of genjava error caused by not listed message_generation

- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/cfg/OverlayTextInterface.cfg
- jsk_rviz_plugins/python/jsk_rviz_plugins/overlay_text_interface.py
- jsk_rviz_plugins/setup.py
Modified:
- jsk_rviz_plugins/CMakeLists.txt
Added:
- jsk_rviz_plugins/cfg/OverlayTextInterface.cfg
- jsk_rviz_plugins/python/jsk_rviz_plugins/__init__.py
- jsk_rviz_plugins/python/jsk_rviz_plugins/overlay_text_interface.py
- jsk_rviz_plugins/setup.py
> [jsk_rviz_plugins] Add utility python class to publish OverlayText

- jsk_rviz_plugins/scripts/float32_to_overlay_text.py
Added:
- jsk_rviz_plugins/scripts/float32_to_overlay_text.py
> [jsk_rviz_plugins] Utility script to draw float32 as overlay text

- jsk_interactive_markers/jsk_interactive_marker/config/biped_urdf_model_marker.yaml
- jsk_interactive_markers/jsk_interactive_marker/launch/out_of_body_marker.launch
使い回しができるように，幽体離脱マーカーを上げる最小限のlaunchを追加しました．
> [jsk_interactive_marker] add out_of_body_marker.launch

- jsk_interactive_markers/jsk_interactive_marker/launch/out_of_body_marker.launch
by @orikuma san https://github.com/start-jsk/rtmros_common/pull/893
> [out_of_body_marker.launch] odom_on_ground will be deprecated

- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
this is caused with upgraded matplotlib.
reported at: https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/2
Modified:
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py
> Except NavigationToolbar ImportError from matplotlib

- jsk_interactive_markers/jsk_interactive_marker/euslisp/display-robot-state.l
- jsk_interactive_markers/jsk_interactive_marker/package.xml
- jsk_interactive_markers/jsk_interactive_marker/scripts/semantic_robot_state_generator.py
It should be much easier and stable than using furutaractive
> [jsk_interactive_marker] Utility script and euslisp function to use moveit_msgs/DispalayRobotState

- jsk_rviz_plugins/src/overlay_diagnostic_display.cpp
- jsk_rviz_plugins/src/overlay_diagnostic_display.h
reference: [http://kekkonsiki-bideo.biz/gazou/youtube/3n836PcugLE.jpg](http://kekkonsiki-bideo.biz/gazou/youtube/3n836PcugLE.jpg)
> [jsk_rviz_plugins/OverlayDiagnostics] Add new style

- jsk_interactive_markers/jsk_interactive_marker/cfg/CameraInfoPublisher.cfg
- jsk_interactive_markers/jsk_interactive_marker/cfg/FootstepMarker.cfg
- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractivePointCloud.cfg
- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractiveSetting.cfg
- jsk_interactive_markers/jsk_interactive_marker/cfg/PointCloudCropper.cfg
- jsk_rviz_plugins/cfg/ContactStateMarker.cfg
- jsk_rviz_plugins/cfg/OverlayTextInterface.cfg
related https://github.com/jsk-ros-pkg/jsk_common/issues/1359
> remove dynamic_reconfigure.parameter_generator, which only used for rosbuild

- jsk_rviz_plugins/src/overlay_image_display.cpp
tag: bug, pkg/jsk_rviz_plugins
This is much simpler to specify expected image size.
Specifying image size with both w/h is too complicated.
Fix https://github.com/jsk-ros-pkg/jsk_visualization/issues/597
> Keep aspect ratio with only specified width for OverlayImage

- README.md
> Fix style of 'Deb Build Status' in README.md

- jsk_rviz_plugins/package.xml
> Cleanup jsk_rviz_plugins package.xml

- doc/jsk_interactive_marker/display_robot_state.md
fix the name of launch file in documents.
> [doc/jsk_interactive_marker/display_robot_state.md] fix name of launch file

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
before
https://drive.google.com/open?id=0B9P1L--7Wd2vaXo0ZVFiSGVCRjA
after
https://drive.google.com/open?id=0B9P1L--7Wd2vTE4wWmpab2QtMmM
> [jsk_interactive_markers] Set marker pose periodically for re-enabling on rviz

- doc/jsk_interactive_marker/nodes/transformable_server_sample.md
- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractiveSetting.cfg
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_object.h
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_object.cpp
> [jsk_rviz_plugins] Show description of only object which is selected

- jsk_rviz_plugins/src/footstep_display.cpp
Footsteps are visualized by using offset parameter.
merge after https://github.com/jsk-ros-pkg/jsk_common_msgs/pull/12
> [jsk_rviz_plugins] add offset to footstep_display.h

- .travis.rosinstall.jade
- .travis.yml
use deb package of view_controller_msgs
> use deb for jade

- jsk_rviz_plugins/src/overlay_diagnostic_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_utils.h
this should fix problem on jade (u and v) http://build.ros.org/job/Jbin_uU64__jsk_rviz_plugins__ubuntu_utopic_amd64__binary/
> fix for Ogre >= 1.9

- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/polygon_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/urdf_model_marker_main.cpp
- jsk_rviz_plugins/src/overlay_text_display.cpp
see
- https://github.com/jsk-ros-pkg/jsk_common/pull/1462
- https://github.com/jsk-ros-pkg/jsk_common/issues/1461
> Stop using deprecated jsk_topic_tools/log_utils.h

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
> Fix #655: Fix frame_id of tf published by marker_6dof

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
> marker_6dof: publish tf after transformed to frame_id_, update is published with fixed frame of rviz

- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/rviz_plugins/transformable_marker_operator.h
- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/src/cancel_action.h
- jsk_rviz_plugins/src/empty_service_call_interface.h
- jsk_rviz_plugins/src/object_fit_operator.h
- jsk_rviz_plugins/src/record_action.h
- jsk_rviz_plugins/src/robot_command_interface.h
- jsk_rviz_plugins/src/select_point_cloud_publish_action.h
- jsk_rviz_plugins/src/tablet_controller_panel.h
- jsk_rviz_plugins/src/yes_no_button_interface.h
> migration to kinetic

- jsk_interactive_markers/jsk_interactive_marker/package.xml
related to https://github.com/jsk-ros-pkg/jsk_visualization/commit/e80c2de6880d1bf7ccced232d26d6522b64ea550#commitcomment-20872551
> [jsk_interactive_marker][package.xml] remove pr2eus_moveit from dependency

- .travis.yml
- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/package.xml
see https://github.com/ros/rosdistro/pull/13886#issuecomment-279832181
> package.xml/CMakeLists.txt : remove depends to wxwidgets

- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/cfg/ClassificationResultVisualizer.cfg
- jsk_rviz_plugins/scripts/classification_result_visualizer.py
> [jsk_rviz_plugins] add marker publisher for classification result

- jsk_rviz_plugins/cfg/ClassificationResultVisualizer.cfg
- jsk_rviz_plugins/scripts/classification_result_visualizer.py
Addressed #667 
@k-okada Sorry, need some bugfix...
> [jsk_rviz_plugins][classification_result_visualizer] minor bugfix

- .travis.yml
This enables us to remove cron job from jenkins.
> Trigger the build of jsk-docs.rtd.org by travis

- .travis.yml
- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractiveSetting.cfg
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/rviz_plugins/transformable_marker_operator.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_object.h
- jsk_interactive_markers/jsk_interactive_marker/launch/sample_transformable_markers_client.launch
- jsk_interactive_markers/jsk_interactive_marker/package.xml
- jsk_interactive_markers/jsk_interactive_marker/src/rviz_plugins/transformable_marker_operator.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_object.cpp
Depends on https://github.com/jsk-ros-pkg/jsk_recognition/pull/2148
I'd like to spawn mesh models using rviz panel.
> Object 3d annotation using transformable interactive marker

- jsk_rviz_plugins/package.xml
- jsk_rviz_plugins/scripts/classification_result_visualizer.py
Support `geometry_msgs/PoseArray`, `jsk_recognition_msgs/PeoplePoseArray` and `posedetection_msgs/ObjectDetection` to be visualized.
Originally `jsk_recognition_msgs/BoundingBoxArray` is only supported.
> jsk_rviz_plugins: class_result_vis: add more types to vislalize

- jsk_rviz_plugins/src/polygon_array_display.cpp
- jsk_rviz_plugins/src/tablet_controller_panel.cpp
small correction of std namespace.
> [jsk_rviz_plugins] fix std::isnan to make it compile under Ubuntu 16.04 / gcc 5

- jsk_rqt_plugins/sample_scripts/sample_hist_pub.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
Reverts jsk-ros-pkg/jsk_visualization#688
> Revert "[jsk_rqt_plugins/HistogramPlot] modify to correctly run on kinetic"

- jsk_interactive_markers/jsk_interactive_marker/package.xml
though @iory 's patch to upstream (https://github.com/ros/rosdistro/pull/19057) has merged, I think @naoki-mizuno 's patch is still effective
to respect his contribution, I think we should merge his commit to our source tree
> @naoki-mizuno Remove newline and leading spaces from package.xml

- jsk_rqt_plugins/sample_scripts/sample_hist_pub.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
this PR is improved PR of #688.
it works with `matplotlib` `1.5.1`
> [jsk_rqt_plugins] fix hist.py to work on kinetic

- jsk_rviz_plugins/src/camera_info_display.cpp
Copying image pixel-by-pixel is very slow and unneeded when drawing camera info image.
> [jsk_rviz_plugins] Optimize camera info displaying

- jsk_rviz_plugins/src/camera_info_display.cpp
To find solution of #713, @iory please add image of this udpate
> add error message to status

- jsk_rviz_plugins/src/target_visualizer_display.cpp
- jsk_rviz_plugins/src/target_visualizer_display.h
Related to #719 
I changed to make sure that visualizer_ is explicitly initialized.
> [jsk_rviz_plugins/target_visualize] Add visualizer_ initilized flags

- doc/jsk_interactive_marker/nodes/marker_6dof.md
Summary
- Split `topics` into `subscribing topics` and `publishing topics`
- Correct topic name
- Add missing params
> [doc] Update doc of marker_6dof

- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
current code does not make sense
> [jsk_rqt_plugins] load rosparam correctly in button_general.py

- jsk_interactive_markers/jsk_interactive_marker/src/yaml_menu_handler.cpp
Moved from #751 
cf. jsk-ros-pkg/jsk_travis#385
> Remove unnecessary ROS_INFO

- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.h
> [jsk_rviz_plugins/OverlayImage] Add property to ignore alpha channel of the image

- jsk_rviz_plugins/src/overlay_menu_display.cpp
- jsk_rviz_plugins/src/overlay_menu_display.h
- jsk_rviz_plugins/src/overlay_picker_tool.cpp
> Add property to set position of overlay menu

- .travis.yml
- jsk_rqt_plugins/CMakeLists.txt
- jsk_rviz_plugins/src/bounding_box_display_common.h
- jsk_rviz_plugins/src/camera_info_display.h
- jsk_rviz_plugins/src/footstep_display.h
- jsk_rviz_plugins/src/polygon_array_display.h
- jsk_rviz_plugins/src/segment_array_display.h
- jsk_rviz_plugins/src/torus_array_display.h
related to #765 
fix test failure in jsk_rqt_plugins
error log for kinetic test: https://api.travis-ci.org/v3/job/670881267/log.txt
> fix test failure in jsk_rqt_plugins

- jsk_rviz_plugins/scripts/string_to_overlay_text.py
This script  convert one or more std_msgs/String topic(s) into one jsk_rviz_plugins/OverlayText topic.
> Add string_to_overlay_text

- jsk_rviz_plugins/src/bounding_box_display_common.h
- jsk_rviz_plugins/src/overlay_utils.cpp
- jsk_rviz_plugins/src/overlay_utils.h
- jsk_rviz_plugins/src/pictogram_array_display.cpp
- jsk_rviz_plugins/src/pictogram_display.cpp
- jsk_rviz_plugins/src/segment_array_display.cpp
- jsk_rviz_plugins/src/view_controller/tablet_view_controller.cpp
@pbeeson thanks for iterating, fixed conflict and mergeed
Closes #770
> Fix programming issues where functions were not getting return values, and variables were not being declared for types

- doc/requirements.txt
add six in doc/requirements to avoid build failure.
> [doc] add six in doc/requirements.txt

- README.md
> [readme] fix doc link

- jsk_interactive_markers/jsk_interactive_marker/scripts/transformable_markers_client.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
> [jsk_interactive_markers][jsk_rqt_plugins] fix yaml load

- jsk_rviz_plugins/config/piechart_sample.rviz
- jsk_rviz_plugins/launch/piechart_sample.launch
- jsk_rviz_plugins/samples/piechart_sample.py
I add piechart sample
```bash
roslaunch jsk_rviz_plugins piechart_sample.launch
```
> [jsk_rviz_plugins] add piechart sample

- .github/workflows/dependency.yml
- jsk_rviz_plugins/package.xml
closes #829
4278312 failed as expected https://github.com/jsk-ros-pkg/jsk_visualization/runs/3715542652?check_suite_focus=true
031d7c7 fixed https://github.com/jsk-ros-pkg/jsk_visualization/runs/3715552387?check_suite_focus=true
> add dependency.yml to check resolve circular dependency in jsk_rviz_plugins/package.xml

- jsk_interactive_markers/jsk_interactive_marker/euslisp/display-robot-state.l
- jsk_interactive_markers/jsk_interactive_marker/euslisp/sample-display-robot-state.l
- jsk_interactive_markers/jsk_interactive_marker/launch/sample_display_robot_state.launch
jaxon_ros_bridge is a private repository and currently JAXON RED model in rtmros_tutorials is broken. https://github.com/start-jsk/rtmros_tutorials/issues/601
So I changed this demo to run with PR2.
https://user-images.githubusercontent.com/9410362/142151912-9a072225-bf60-4647-ae05-94a8eebdf0dd.mp4
> Fix sample display robot state demo

- jsk_rviz_plugins/src/bounding_box_display_common.h
this PR change to show only valid bboxes.
current master allocate the bboxes first, and skip if the box is invalid, which cause to show the 1m cube at the originl point.
this PR change to first check if bboxes are valid or not, and allocate it.
I also change to check if `bboxes.box[i].header.frame_id` is empty or not.
https://user-images.githubusercontent.com/9300063/200168499-83ef048c-0cfd-4b29-8955-26bea110c073.mp4
https://user-images.githubusercontent.com/9300063/200168503-7d3e9624-5c41-4aec-bb12-0418bc251cf0.mp4
```python
import numpy as np
import rospy
from jsk_recognition_msgs.msg import BoundingBox
from jsk_recognition_msgs.msg import BoundingBoxArray
class Spam(object):
def __init__(self):
self.pub = rospy.Publisher('~hoge', BoundingBoxArray, queue_size=1)
self.timer = …
```
> [jsk_rviz_plugins] allocate only valid bboxes

- jsk_rqt_plugins/src/jsk_rqt_plugins/image_view2_wrapper.py
now noetic fails because mouse event in not int type.
I fix to change it to int.
> return int in mouse event

- jsk_rqt_plugins/plugin.xml
this PR fix plugin category.
some plugins related to services are in visualization folder.
I moved them into services folders.
> fix plugin category

- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/label.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/tabbed_button_general.py
SOMOSOMO, why do we put file path by string???????????????????
i feel like im in 1970s. (mouse is from 1983)
https://en.wikipedia.org/wiki/Apple_Lisa
this PR change to use QFileDialog to open yaml file.
I only tested on noetic
https://user-images.githubusercontent.com/9300063/234813532-4c18cc03-032a-4950-a449-6ca39016061e.mp4
> use QFileDialog for file select

- jsk_rqt_plugins/src/jsk_rqt_plugins/tabbed_button_general.py
- jsk_rqt_plugins/test/test_rqt_plugins.test
test to check https://github.com/jsk-ros-pkg/jsk_visualization/pull/879
it was not worked on all distros...
> add test to check (ServiceButtonGeneralWidget_in_tab

- jsk_rqt_plugins/package.xml
> drop obsolete (and broken urlgrabber dependency)
