jsk-ros-pkg/jsk_visualization

- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_object.h
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_object.cpp
- jsk_rviz_plugins/msg/TransformableMarkerOperate.msg
transformable_markerにmeshを表示する機能を加えました。
msgを変えましたが、 
https://github.com/jsk-ros-pkg/jsk_common/commit/32652fb76e090f8929a5aae8482d86a419554d54
と同じたぐいの変更なので大丈夫です。
> add_mesh_model_in_transformable_marker

- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/plugin_description.xml
- jsk_rviz_plugins/src/pose_array_display.cpp
- jsk_rviz_plugins/src/pose_array_display.h
Request from @garaemon .
Update to make it able to change type of pose.
Until upstream merge almost same PR.
> [jsk_rviz_plugins] add tmp pose array display

- jsk_rviz_plugins/src/simple_occupancy_grid_array_display.cpp
need to release new version of jsk_recognition
> [jsk_rviz_plugins] Use jsk_pcl_ros/geo_util to reconstruct 3d information in SimpleOccupancyGridArrayDisplay

- jsk_rviz_plugins/src/overlay_image_display.cpp
Support alpha channel if image_encoding is BGRA8 or RGBA8
> [jsk_rviz_plugins/OverlayImage] Support alpha channel 

- jsk_rviz_plugins/src/pose_array_display.cpp
となっていて，（ARROWのときはあってたのに，）AXESだと表示が間違えていてので
になるようにしました．
> fix coords bug

- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.h
1.  Easily set width or height with correct aspect ratio (also available static width and height setup)
2.  Automatically adjust size changing topic image
> [jsk_rviz_plugins][OverlayImage] Automatically setup size with negative value

- jsk_interactive_markers/jsk_interactive_marker/src/urdf_control_marker.cpp
Visualize furutaractive marker without clicking urdf_control_marker without clicking urdf_control_marker by calling dynamic_tf in constructor.
> [jsk_interactive_marker/urdf_control_marker] Visualize furutaractive marker without clicking urdf_control_marker

- jsk_interactive_markers/jsk_interactive_marker/src/urdf_control_marker.cpp
instead of ros::service::waitForService in order to wait
dynamic_tf_publisher. Use different API leads potential bugs
> [jsk_interactive_marker] Use ros::ServiceClient::waitForExistence

- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
I'm not sure but this may fix problem at -> https://github.com/jsk-ros-pkg/jsk-ros-pkg-unreleased/commit/77159929a0c41d3b92ffae098d1c02c3862430ee
```
-- Using CATKIN_TEST_RESULTS_DIR: /home/travis/ros/ws_jsk-ros-pkg-unreleased/build/drc_task_common_deprecated/test_results
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Found gtest sources under '/usr/src/gtest': gtests will be built
-- catkin 0.5.90
-- Using these message generators: gencpp;geneus;genlisp;genpy
CMake Error at …
```
> add jsk_recognition_msgs to catkin_package(CATKIN_DEPEND)

- jsk_rviz_plugins/scripts/relay_screenshot.py
It depends on ScreenshotListener tool of jsk_rviz_plugins.
For example, `rosrun jsk_rviz_plugins relay_screenshot.py ~input:=/region_growing_multi_plane_segmentation/output/polygons`
> [jsk_rviz_plugins] A script to take screenshot of rviz when a topic is published: relay_screenshot.py

- jsk_rviz_plugins/src/bounding_box_array_display.cpp
Modified:
jsk_rviz_plugins/src/bounding_box_array_display.cpp
> [jsk_rviz_plugins] Disable `show coords` in default in BoundingBoxDisplay

- jsk_interactive_markers/jsk_interactive_marker/cfg/FootstepMarker.cfg
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/footstep_marker.h
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/interactive_marker_helpers.h
- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
- jsk_interactive_markers/jsk_interactive_marker/src/interactive_marker_helpers.cpp
Modified:
- jsk_interactive_markers/jsk_interactive_marker/cfg/FootstepMarker.cfg
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/footstep_marker.h
- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
> [jsk_interactive_marker] Add ~use_2d parameter to remove z-axis translation  and rotation around x-y axis

- jsk_interactive_markers/jsk_interactive_marker/euslisp/transformable-object-util.l
jsk_visualizationのtransformable markerをeusから使うためutil関数です。
もともとdrc_task_commonの下にあったものを整理しました。
DRCと関係しないプログラムからも使うことが多いので、できればこちらに置きたいです。
> [jsk_interactive_marker/euslisp] add transformable-object-util.

- jsk_rviz_plugins/CMakeLists.txt
see https://github.com/ros-visualization/rviz/pull/979
our package start failing recently, due to
```
00:56:15 /tmp/binarydeb/ros-indigo-jsk-rviz-plugins-1.0.29/src/quiet_interactive_marker_display.cpp:40: undefined reference to `rviz::InteractiveMarkerDisplay::InteractiveMarkerDisplay()'
00:56:15 CMakeFiles/jsk_rviz_plugins.dir/src/quiet_interactive_marker_display.cpp.o: In function `rviz::InteractiveMarkerDisplay::~InteractiveMarkerDisplay()':
00:56:15 /opt/ros/indigo/include/rviz/default_plugin/interactive_marker_display.h:65: undefined reference to `vtable for rviz::InteractiveMarkerDisplay'
00:56:15 CMakeFiles/jsk_rviz_plugins.dir/src/quiet_interactive_marker_display.cpp.o:(.data.rel.ro._ZTIN16jsk_rviz_plugins29QuietInteractiveMarkerDisplayE[_ZTIN16jsk_rviz_plugins29QuietInteractiveMa …
```
> add rviz_DEFAULT_PLUGIN_LIBRARIES

- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
When subscribing HistgramWithRangeArray in rqt_histogram_plot like /histgram_array/histograms[0], rqt_histogram_plot cause an error at https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py#L161  because self._rosdata.sub.data_class is HistgramWithRangeArray.
> [jsk_rqt_plugins] Check class type of data instead of subscribed topic type in rqt_histgram_plot to support HistgramWithRangeArray

- jsk_rviz_plugins/scripts/rosconsole_overlay_text.py
> [jsk_rviz_plugins] Show colorized ros logging on rviz overlay text

- jsk_rviz_plugins/src/video_capture_display.cpp
The RGB channel order is wrong in video_capture plugin.
Fix #583
!!!The chair is **RED**!!!
**Before**
**After**
> [jsk_rviz_plugins] Convert RGB to BGR precisely in video capturing

- jsk_rviz_plugins/src/bounding_box_array_display.cpp
- jsk_rviz_plugins/src/bounding_box_array_display.h
Why?
----
Currently, bounding boxes visualization is stopped if invalid box is included.
This PR enables the plugin skip the invalid box with warning message and shows valid ones.
cc @furushchev
> [jsk_rviz_plugins] Show valid boxes even if invalid box is included

- doc/jsk_interactive_marker/nodes/transformable_server_sample.md
- jsk_interactive_markers/jsk_interactive_marker/cfg/InteractiveSetting.cfg
- jsk_interactive_markers/jsk_interactive_marker/doc
- jsk_interactive_markers/jsk_interactive_marker/include/jsk_interactive_marker/transformable_interactive_server.h
- jsk_interactive_markers/jsk_interactive_marker/src/transformable_interactive_server.cpp
There are too many manipulators with many objects on rviz.
1. Show interactive manipulator only when the object is selected.
2. Add menu to enable/disable the manipulator.
https://drive.google.com/open?id=0B9P1L--7Wd2vQmpoTDcyZHRtNFU
Labels: feature, pkg/jsk_interactive_marker, documentation
> [jsk_interactive_marker] Mode to display interactive manipultor only when selected

- jsk_rviz_plugins/src/overlay_picker_tool.cpp
as after processing a group with no overlay item, it was still returning true by default. It needed to return false to continue the seach
> handleDisplayClick was not going past first group

- jsk_rviz_plugins/src/overlay_text_display.cpp
- jsk_rviz_plugins/src/overlay_text_display.h
> [jsk_rviz_plugins] Show available fonts using enum property in OverlayText

- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
see
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
- https://github.com/jsk-ros-pkg/jsk_recognition/pull/1914
> Migrate srv files from jsk_pcl_ros to jsk_recognition_msgs

- .travis.rosinstall.hydro
- .travis.yml
- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
- jsk_interactive_markers/jsk_interactive_marker/package.xml
- jsk_interactive_markers/jsk_interactive_marker/src/footstep_marker.cpp
Depends on https://github.com/jsk-ros-pkg/jsk_recognition/pull/1827
> [jsk_interactive_marker] Remove dependency on jsk_pcl_ros for separated build

- doc/jsk_interactive_marker/nodes/marker_6dof.md
I found mistake in doc of https://github.com/jsk-ros-pkg/jsk_visualization/pull/657 .
> [jsk_interactive_marker/doc] add indents to marker_6dof doc.

- jsk_rviz_plugins/src/bounding_box_display_common.h
- jsk_rviz_plugins/src/footstep_display.cpp
- jsk_rviz_plugins/src/people_position_measurement_array_display.cpp
- jsk_rviz_plugins/src/polygon_array_display.cpp
- jsk_rviz_plugins/src/polygon_array_display.h
- jsk_rviz_plugins/src/simple_occupancy_grid_array_display.cpp
- jsk_rviz_plugins/src/target_visualizer_display.cpp
- jsk_rviz_plugins/src/torus_array_display.cpp
Closes #697 
In this PR, a warning is displayed when received messages are not valid.
> jsk_rviz_plugins: warn on missing frame_id

- jsk_rviz_plugins/src/tf_trajectory_display.cpp
Same issue as https://github.com/jsk-ros-pkg/jsk_common/pull/1584
When building jsk_topic_tools on Ubuntu 18.04 with Ros Melodic and Boost 1.65.1.0ubuntu1 I get this error:
```
/home/laurenz/catkin_ws/src/jsk/jsk_rviz_plugins/src/tf_trajectory_display.cpp: In member function ‘virtu
al void jsk_rviz_plugins::TFTrajectoryDisplay::update(float, float)’:                                    
/home/laurenz/catkin_ws/src/jsk/jsk_rviz_plugins/src/tf_trajectory_display.cpp:136:25: error: ‘format’ is
not a member of ‘boost’                                                                                 
(boost::format("Failed transforming from frame '%s' to frame '%s'")                     
^~~~~~ …
```
> Add #include <boost/format.hpp>

- jsk_rqt_plugins/package.xml
In plot_2d.py, sklearn is used.
https://github.com/jsk-ros-pkg/jsk_visualization/blob/master/jsk_rqt_plugins/src/jsk_rqt_plugins/plot_2d.py#L24
> [jsk_rqt_plugins] Add dependency of sklearn

- jsk_interactive_markers/jsk_interactive_marker/package.xml
`jsk_recognition_utils` package is installed in dependent pacakges such as `jsk_rviz_plugins`, but `jsk_recognition_utils` is imported or included in some files in `jsk_interactive_marker` package (e.g. jsk_interactive_marker/scripts/transformable_markers_client.py). 
So I think it desirable to explicitly install that package from `jsk_interactive_marker`.
> [jsk_interactive_marker] Explicitly resolve dependency for jsk_recognition_utils in package.xml

- jsk_rqt_plugins/sample_scripts/sample_hist_pub.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/hist.py
`Kinetic` uses `qt5`, and `qt5` has different module structure.
I refactor codes and update to use correct module for kinetic.
You can check with
```
roslaunch jsk_perception sample_bof_object_recognition.launch
roslaunch jsk_rqt_plugins sample_histogram.launch
```
> [jsk_rqt_plugins/HistogramPlot] modify to correctly run on kinetic

- jsk_rviz_plugins/src/polygon_array_display.cpp
- jsk_rviz_plugins/src/polygon_array_display.h
> add enable lighitng property in polygon_array_display

- jsk_rviz_plugins/src/video_capture_display.cpp
Hi,
When I use ``VideoCapture`` plugin on Kinetic/Xenial, lots of warnings are displayed.
```
[ INFO] [1531911783.631987034]: output.avi do not exists
[ INFO] [1531911783.632022863]: dirname: .
[ WARN] [1531911783.671459216]: force to disable capturing
[ INFO] [1531911788.681274189]: updateStartCapture
[ INFO] [1531911788.681339840]: start capturing
static QPixmap QPixmap::grabWindow(WId, int, int, int, int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
static QPixmap QPixmap::grabWindow(WId, int, int, int, int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
static QPixmap QPixmap::grabWindow(WId, int, int, int, int) is deprecated, use QScreen::grabWindow() instead. Defaulting to primary screen.
static QPixmap …
```
> [jsk_rviz_plugins] use QScreen::grabWindow() instead of QPixmap::grabWindow

- jsk_rviz_plugins/src/overlay_image_display.cpp
* In order not to subscribe image topic when rviz startups with
OverlayImage display disabled, always verify if the display is
enabled before the display subscribes topic.
> Do not subscribe image topic when rviz startups in OverlayImage display

- jsk_rviz_plugins/src/camera_info_display.cpp
* Use %u instead of %lu to print Ogre::Texture::getWidth() and
Ogre::Texture::getHeight() because they return uint32.
https://www.ogre3d.org/docs/api/1.9/class_ogre_1_1_texture.html#a03b77fa04181bc3bd30323555b425667
The following warning will disappear after merging this PR.
```
/home/ryohei/gitai/catkin_ws/src/jsk_visualization/jsk_rviz_plugins/src/camera_info_display.cpp: In member function ‘virtual void jsk_rviz_plugins::CameraInfoDisplay::drawImageTexture()’:
/home/ryohei/gitai/catkin_ws/src/jsk_visualization/jsk_rviz_plugins/src/camera_info_display.cpp:369:1173: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘Ogre::uint32 {aka unsigned int}’ [-Wformat=]
/home/ryohei/gitai/catkin_ws/src/jsk_visualization/jsk_rviz_plugins/src/camera_info_disp …
```
> Fix format specifier

- jsk_rqt_plugins/package.xml
* image_pipeline is a meta package and normal ros packages are not
intended to depend on meta packages.
* `catkin build` reports it as warning as following:
> Replace image_pipeline with image_publisher

- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.h
* Add an editable enum field to specify transport hint on
OverlayImage display.
* raw, compressed and theora are listed as pre-defined transport
hints.
> Add transport hint field to OverlayImage display

- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/src/camera_info_display.cpp
- jsk_rviz_plugins/src/camera_info_display.h
- jsk_rviz_plugins/src/image_transport_hints_property.cpp
- jsk_rviz_plugins/src/image_transport_hints_property.h
- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.h
This PR is a rebased code of https://github.com/jsk-ros-pkg/jsk_visualization/pull/735
* Add field to choose transport hints for CameraInfo display.
* Add ImageTransportHintsProperty class to share code with CameraInfoDisplay and OverlayImageDisplay.
> Transport hint for camera info

- jsk_rviz_plugins/src/overlay_image_display.cpp
* Use memcpy to copy image data from cv::Mat to QImagee instead of use
QImage::setPixel() many times for optimization.
> [jsk_rviz_plugins/OverlayImageDisplay] Use memcpy to copy image data

- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/src/ambient_sound_display_groovy.cpp
- jsk_rviz_plugins/src/ambient_sound_display_groovy.h
- jsk_rviz_plugins/src/bounding_box_display_common.h
- jsk_rviz_plugins/src/camera_info_display.h
- jsk_rviz_plugins/src/facing_visualizer.h
- jsk_rviz_plugins/src/footstep_display.h
- jsk_rviz_plugins/src/normal_display.cpp
- jsk_rviz_plugins/src/normal_display.h
- jsk_rviz_plugins/src/normal_visual.h
- jsk_rviz_plugins/src/overlay_diagnostic_display.cpp
- jsk_rviz_plugins/src/overlay_diagnostic_display.h
- jsk_rviz_plugins/src/overlay_image_display.cpp
- jsk_rviz_plugins/src/overlay_image_display.h
- jsk_rviz_plugins/src/overlay_utils.h
- jsk_rviz_plugins/src/pictogram_display.h
- jsk_rviz_plugins/src/polygon_array_display.h
- jsk_rviz_plugins/src/segment_array_display.h
- jsk_rviz_plugins/src/simple_occupancy_grid_array_display.h
- jsk_rviz_plugins/src/torus_array_display.h
- jsk_rviz_plugins/src/twist_stamped_display.h
- jsk_rviz_plugins/src/video_capture_display.h
current `jsk_rviz_plugins` is built with C++11 with `std::shared_ptr`. (see #710)
This causes rviz load error and segmentation fault in Indigo. (see https://github.com/PointCloudLibrary/pcl/issues/619#ref-pullrequest-151717701)
I support to build old fashion style when ROS version is indigo.
> support jsk_rviz_plugin to be loaded in indigo

- jsk_rviz_plugins/scripts/motor_states_temperature_decomposer.py
以下のようなwariningを出ないようにするために、引数queue_sizeを追加しました。
queue_sizeはHydroで追加された引数です。
jsk_rviz_pluginには他にもqueue_sizeを指定せずにPublisherを立ち上げているコードがあるようです。
```
/opt/ros/kinetic/lib/jsk_rviz_plugins/motor_states_temperature_decomposer.py:78: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
g_text_publisher = rospy.Publisher("max_temparature_text", OverlayText)
/opt/ros/kinetic/lib/jsk_rviz_plugins/motor_states_temperature_decomposer.py:28: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
g_effort_publishers[name] = …
```
> [motor_states_temperature_decomposer.py]add queue_size

- doc/requirements.txt
Travis build of #758 is failing.
From https://travis-ci.org/jsk-ros-pkg/jsk_visualization/jobs/647611272#L1500
```
++ sudo apt-get update -q
Ign https://esm.ubuntu.com trusty-infra-security InRelease
Ign https://esm.ubuntu.com trusty-infra-updates InRelease
Ign https://esm.ubuntu.com trusty-infra-security Release.gpg
Ign https://esm.ubuntu.com trusty-infra-updates Release.gpg
Ign https://esm.ubuntu.com trusty-infra-security Release
Ign https://esm.ubuntu.com trusty-infra-updates Release
Err https://esm.ubuntu.com trusty-infra-security/main amd64 Packages
Received HTTP code 403 from proxy after CONNECT
Err https://esm.ubuntu.com trusty-infra-updates/main amd64 Packages
Received HTTP code 403 from proxy after CONNECT
Get:1 http://packages.ros.org trusty InRelease [4669 B]
Get:2 …
```
> Update jsk_travis to 0.5.7

- jsk_rviz_plugins/src/overlay_text_display.cpp
- jsk_rviz_plugins/src/overlay_text_display.h
1) Add shadows to text overlays (with an invert toggle for dark text on black backgrounds), but simply using the QPainter to draw black (or white for inverted) text first, offset by 1 from the actual text.
2) Split overriding of BG color from overriding of FG color/size, so that users that might want to add a background color can still have published FG colors used (which might have semantics defined by the publisher, like Green for good and Red for bad).
> Improve Overlay Visibility

- jsk_rviz_plugins/src/pose_array_display.cpp
fix #785 
warn that `jsk_rviz_plugins/PoseArrayDisplay` is deprecated when user uses it.
I update to show this warning on Kinetic and upper version.
cc. @pazeshun
> [jsk_rviz_plugins] add warn for deprecated jsk_rviz_plugins/PoseArrayDisplay

- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
add `service_type` in rqt_service_buttons and rqt_service_radio_buttons.
with this PR, we can use `std_srvs/Empty` and `std_srvs/Trigger`
```bash
- name: 'Trigger button'
service: 'trigger'
service_type: 'Trigger'
column: 0
- name: 'Empty button'
service: 'empty'
service_type: 'Empty'
column: 0
```
> [jsk_rqt_plugins] add service_type and support Trigger for rqt service button

- .travis.yml
- doc/add_img_tables_to_index.py
- doc/conf.py
- doc/requirements.txt
- doc/setup.sh
- add escape in latex title
- support japanese for latex build in readthedoc
- fix add_img_tables_to_index.py for python3
- add missing extensions in conf.py
I tested with my readthedoc project.
> [doc] Fix doc build

- jsk_rqt_plugins/resource/service_button_layout.yaml
- jsk_rqt_plugins/sample_scripts/sample_service_buttons.py
- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
merge after #780 and #791 
Support `SetBool` service for `rqt_service_buttons`.
You can try with following command:
```bash
roslaunch jsk_rqt_plugins sample_service_buttons.launch
```
> [jsk_rqt_plugins] Support SetBool for Service Buttons

- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
`SetBool` に失敗した時に、ボタンの「押されている」「押されていない」を戻すようにしました。
> [jsk_rqt_plugins/button_general.py] reset button if SetBool failed

- jsk_rqt_plugins/sample/sample_service_buttons_wo_perspective.launch
- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
For using rqt_service_buttons(button_general.py) without perspective file
> fix for using button_general.py without perspective file

- jsk_rqt_plugins/src/jsk_rqt_plugins/button_general.py
* `*column_indices` expects to be an array of integers and the length
should be equal or longer than 2.
* If column_indices is just an array of a single integer (length is
1), do not apply sum with expanding a list argument.
> Support single button setup in ServiceButtons plugin

- jsk_rviz_plugins/src/overlay_text_display.cpp
Addresses https://github.com/jsk-ros-pkg/jsk_visualization/issues/801
> #801 added a regex for "color: XXX;" pattern to have a properly colored shadow

- jsk_rviz_plugins/src/pie_chart_display.cpp
Since `drawPlot` was called before `setPosition` and `setDimensions` (around line 173), updates of position and size from Rviz GUI were never taken into account. 
Another problem was that the chart needed to receive a new, different value to update these parameters. I corrected that by adding `update_required_ = true` in all the display parameters update functions.
> Resize and repositioning of PieChart wasn't working, corrected.

- doc/jsk_rviz_plugins/plugins/pie_chart.md
- jsk_rviz_plugins/src/pie_chart_display.cpp
- jsk_rviz_plugins/src/pie_chart_display.h
[Pie chart] 
You can set the max color and med color at your custom max and med color threshold after enabling `auto color change`.
e.x. 
1. `roslaunch jsk_rviz_plugins piechart_sample.launch`
2. Enable `auto color change` on rviz
3. Set max color (med color)
4. Set max threshold (med threshold)
https://user-images.githubusercontent.com/42209144/143372588-07feb002-7d5d-4d41-a48e-bef074767c5e.mp4
> Change pie chart color at your custom threshold

- jsk_interactive_markers/jsk_interactive_marker/src/marker_6dof.cpp
* The pose in callback function of interactive marker is represented
respect to fixed frame of rviz.
* In order to publish consistent tf transformation, the pose should be
transformed respect to the frame_id which is specified as ros
parameter.
> Resolve fixed frame of rviz

- jsk_rviz_plugins/config/pictogram_sample.rviz
- jsk_rviz_plugins/launch/pictogram_sample.launch
- jsk_rviz_plugins/src/pictogram_display.cpp
PR #759 reported `fa-mendeley` is not displayed correctly. 
I think This because of the plugin uses system font, which is installed by `fonts-font-awesome` deb package, not font defined in fontawesome.dat. So if you remove`fonts-font-awesome`, you can not display most of font correctly as shown in below.
This PR update getFont function to return the correct font family and display all pictgrams
> Fix font name for pictgram

- jsk_rviz_plugins/src/camera_info_display.cpp
`CameraInfo` plugin in `jsk_rviz_plugins` is not visualizing camera info correctly when roi and binning are set.
Following video shows the result of decimated `CameraInfo` in https://github.com/jsk-ros-pkg/jsk_recognition/pull/2713 
Command is `roslaunch jsk_perception sample_robot_to_mask_image.launch gui:=true decimate:=true`
https://user-images.githubusercontent.com/4690682/179243344-3da8f2fd-9757-47d9-8572-e65c5020ae0a.mp4
This PR properly visualizes `CameraInfo` as shown in the following video by properly calculating roi and binning.
https://user-images.githubusercontent.com/4690682/179243701-a8f4ccac-04d7-4ee3-8467-4ef90082010b.mp4
> [jsk_rviz_plugins] Fixed Camera Info visualization

- .github/workflows/config.yml
- jsk_rviz_plugins/src/linear_gauge_display.cpp
If the minimum of the linear gauge is not zero, it incorrectly displays the "progress". This PR fixes it.
Previously non-working config:
Min value 24, max value 25, current value 24.5.
Previous normalized_value would be `min(max(24.5,0), 25) * width / 25 = min(24.5, 25) * width / 25 = 24.5 * width / 25 = almost 100% width`, while it should be 50%.
New normalized value is `min(max(24.5-24, 0), 25 - 24) * width / (25-24) = min(0.5, 1) * width / 1 = 50% width`.
> Fixed linear gague display

- jsk_rviz_plugins/src/overlay_camera_display.cpp
Without this change, adding both OverlayCamera and OverlayImage to one rviz window crashes with:
```
[ WARN] [1669695420.835465329, 1666865132.227821766] [ros.rviz]: OGRE EXCEPTION(4:ItemIdentityException): Overlay with name 'OverlayImageDisplayObject0' already exists! in OverlayManager::create at /build/ogre-1.9-CZD0Iy/ogre-1.9-1.9.0+dfsg1/Components/Overlay/src/OgreOverlayManager.cpp (line 109)
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
what():  OGRE EXCEPTION(4:ItemIdentityException): Overlay with name 'OverlayImageDisplayObject0' already exists! in OverlayManager::create at /build/ogre-1.9-CZD0Iy/ogre-1.9-1.9.0+dfsg1/Components/Overlay/src/OgreOverlayManager.cpp (line 109)
```
I'm not really sure whether it is correct that I made this string different …
> Fix simultaneous display of OverlayCamera and OverlayImage

- jsk_rviz_plugins/cfg/OverlayTextInterface.cfg
- jsk_rviz_plugins/package.xml
- jsk_rviz_plugins/test/test_overlay_text_interface.py
- jsk_rviz_plugins/test/test_overlay_text_interface.test
this only happens in noetic, to fix this we need to fix `OverlayTextInterface.cfg` compatible with `OverText.msg`
```
File "/home/k-okada/catkin_ws/jsk_recognition_ws/devel/lib/python3/dist-packages/jsk_rviz_plugins/msg/_OverlayText.py", line 127, in serialize
except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 393, in _check_types
check_type(n, t, getattr(self, n))
File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 261, in check_type
raise SerializationError('field %s must be an integer type' % field_name)
genpy.message.SerializationError: field width must be an integer type
```
> add test to check 'genpy.message.SerializationError: field width must be an integer type'

- jsk_rviz_plugins/src/overlay_diagnostic_display.h
While building the jsk_rviz_plugins from source on a ubuntu 22.04 system in a catkin workspace, had the following error message. And to fix it, included the _QPainterPath_ header.
> jsk_visualization/jsk_rviz_plugins/src/overlay_diagnostic_display.cpp:388:18: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
>   388 |     QPainterPath path;
> Fix QPainterPath path has incomplete type and cannot be defined

- jsk_rviz_plugins/src/overlay_picker_tool.cpp
this is refactored version of #855 
the magic number `16777248` comes from `QT::Key_Shift`.
```
In [1]: 0x01000020
Out[1]: 16777248
```
https://doc.qt.io/qt-5/qt.html
```
Qt::Key_Shift | 0x01000020
```
> use qt key namespace

- jsk_interactive_markers/jsk_interactive_marker/scripts/transformable_markers_client.py
Because `xrange` is removed on Python3, we face an error here:
https://github.com/jsk-ros-pkg/jsk_visualization/blob/8cfd3b628821c826023ee47e9af62d732d2f6df9/jsk_interactive_markers/jsk_interactive_marker/scripts/transformable_markers_client.py#L68
We can use `range` as `xrange` on Python3 because Python2's `xrange` equals Python3's `range`.
> [jsk_interactive_marker/scripts/transformable_markers_client.py] Fix for Python3

- jsk_rviz_plugins/src/plotter_2d_display.cpp
- jsk_rviz_plugins/src/plotter_2d_display.h
One solution to solve https://github.com/jsk-ros-pkg/jsk_visualization/issues/862 .
Adding `auto_text_size_in_plot` property and if it is enabled, the rviz automatically adjust text size in Plotter2D.
When `auto_text_size_in_plot` is disabled, you can control text size in Plotter2D by editing `text_size_in_plot` manually.
> [jsk_rviz_plugins][Plotter2D] add option to control text size in plot

- .github/workflows/config.yml
fix CI, override node20. See https://github.com/actions/upload-artifact/issues/616#issuecomment-2350667347
c.f. https://github.com/jsk-ros-pkg/jsk_control/pull/790
```
Post job cleanup.
/usr/bin/docker exec  a73c1686824111e1103ab64b9f540a586c9548c53a8213840c21206b2f17403a sh -c "cat /etc/*release | grep ^ID"
OCI runtime exec failed: exec failed: unable to start container process: exec: "/__e/node20/bin/node": stat /__e/node20/bin/node: no such file or directory: unknown
```
> fix CI, override node20 directory.

- jsk_interactive_markers/jsk_interactive_marker/CMakeLists.txt
- jsk_rqt_plugins/CMakeLists.txt
- jsk_rviz_plugins/CMakeLists.txt
- jsk_rviz_plugins/src/camera_info_display.h
- jsk_rviz_plugins/src/overlay_camera_display.cpp
- jsk_rviz_plugins/src/overlay_utils.h
- jsk_rviz_plugins/src/polygon_array_display.h
The first commit supports ROS_DISTRO values out of alphabetic order (also discussed [here](https://github.com/jsk-ros-pkg/jsk_3rdparty/issues/509#issuecomment-2483167494)).
The second is required for OGRE 1.12 (partly Ubuntu noble, definitely Debian bookworm, and newer).
@mqcmd196
> [ROS-O] patches
